# Generated by Django 3.0 on 2019-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_tipo', models.CharField(choices=[('FIS', 'Pessoa Física'), ('JUR', 'Pessoa Jurídica')], max_length=3)),
                ('cliente_nome_fantasia', models.CharField(max_length=200)),
                ('cliente_razao_social', models.CharField(max_length=200)),
                ('cliente_nome_contato', models.CharField(max_length=200)),
                ('cliente_cep', models.CharField(max_length=200)),
                ('cliente_rua', models.CharField(max_length=200)),
                ('cliente_numero', models.CharField(max_length=200)),
                ('cliente_complemento', models.CharField(max_length=200)),
                ('cliente_cidade', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefone', models.CharField(max_length=200)),
                ('cliente_dias_entrega', models.CharField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('cliente_lista_precos', models.PositiveIntegerField()),
                ('cliente_ativo', models.BooleanField()),
            ],
        ),
    ]
