# Generated by Django 3.0 on 2019-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_cep',
            field=models.CharField(help_text='CEP da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_cidade',
            field=models.CharField(help_text='Cidade onde a empresa está localizada', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_complemento',
            field=models.CharField(help_text='Complamento do endereço da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_dias_entrega',
            field=models.CharField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], help_text='Dias de entrega', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_email',
            field=models.EmailField(help_text='Email da pessoa de contato da empresa', max_length=254, unique='true'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_lista_precos',
            field=models.CharField(choices=[('TB1', 'Tabela 1'), ('TB2', 'Tabela 2'), ('TB3', 'Tabela 3')], help_text='Lista de preços da empresa', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_nome_contato',
            field=models.CharField(help_text='Pessoa de contato da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_nome_fantasia',
            field=models.CharField(help_text='Nome da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_numero',
            field=models.CharField(help_text='Número da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_razao_social',
            field=models.CharField(help_text='Razão social da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_rua',
            field=models.CharField(help_text='Rua da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_telefone',
            field=models.CharField(help_text='Telefone da empresa', max_length=200),
        ),
    ]
