# Generated by Django 3.0 on 2019-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0002_auto_20191215_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
