# Generated by Django 3.0 on 2020-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(help_text='Nome do produto', max_length=200)),
                ('produto_codigo', models.DecimalField(decimal_places=2, help_text='Código do produto', max_digits=5)),
                ('produto_ncm', models.CharField(help_text='NCM do produto', max_length=200)),
                ('produto_categoria', models.CharField(help_text='Categoria do produto', max_length=200)),
                ('produto_foto', models.ImageField(help_text='Foto do produto', upload_to='uploads/')),
                ('produto_un_medida', models.DecimalField(decimal_places=2, help_text='Unidade de medida do produto', max_digits=3)),
                ('produto_origem', models.CharField(choices=[('Prop', 'Própria'), ('Terc', 'Terceiros')], help_text='Origem do produto', max_length=4)),
                ('produto_custo', models.DecimalField(decimal_places=2, help_text='Custo do produto', max_digits=5)),
                ('produto_ativo', models.BooleanField()),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='datestamp',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:01:00'),
            preserve_default=False,
        ),
    ]
