# Generated by Django 3.0 on 2020-01-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0004_auto_20200123_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_date', models.DateTimeField(auto_now_add=True)),
                ('pedido_pagamento', models.CharField(choices=[('Cre', 'Crédito'), ('Deb', 'Débito'), ('Din', 'Dinheiro')], help_text='Tipo de pagamento', max_length=3)),
                ('pedido_sub_total', models.DecimalField(decimal_places=2, help_text='Valor total do pedido', max_digits=5)),
                ('pedido_status', models.CharField(choices=[('ent', 'Entregue'), ('aen', 'A entregar'), ('can', 'Cancelado')], help_text='Status do pedido', max_length=3)),
                ('pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rufos.Cliente')),
                ('pedido_produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rufos.Produto')),
            ],
        ),
    ]
