# Generated by Django 3.0 on 2020-01-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0006_auto_20200125_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_cep',
            field=models.CharField(help_text='Exemplo: 00000-000', max_length=200, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_cidade',
            field=models.CharField(max_length=200, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_complemento',
            field=models.CharField(max_length=200, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_dias_entrega',
            field=models.ManyToManyField(help_text='Escolha multiplos dias', related_name='dias_entrega', to='rufos.Entrega', verbose_name='dias de entrega'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_email',
            field=models.EmailField(max_length=254, unique='true', verbose_name='email de contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_nome_contato',
            field=models.CharField(max_length=200, verbose_name='pessoa de contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_nome_fantasia',
            field=models.CharField(max_length=200, verbose_name='nome fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_numero',
            field=models.CharField(max_length=200, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_razao_social',
            field=models.CharField(max_length=200, verbose_name='razão social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_rua',
            field=models.CharField(max_length=200, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_telefone',
            field=models.CharField(help_text='Exemplo: 51 9 0000 0000', max_length=200, verbose_name='telefone de contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_tipo',
            field=models.CharField(choices=[('FIS', 'Pessoa Física'), ('JUR', 'Pessoa Jurídica')], max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.CharField(choices=[('ent', 'Entregue'), ('con', 'Confirmado'), ('can', 'Cancelado')], default='con', help_text='Status do pedido', max_length=3),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_ativo',
            field=models.BooleanField(default=True, verbose_name='produto ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_categoria',
            field=models.CharField(max_length=200, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_codigo',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_custo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='preço custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_foto',
            field=models.ImageField(upload_to='uploads/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_ncm',
            field=models.CharField(max_length=200, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_nome',
            field=models.CharField(max_length=200, verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_origem',
            field=models.CharField(choices=[('Prop', 'Própria'), ('Terc', 'Terceiros')], max_length=4, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_preco_tb1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='preço tabela 1'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_preco_tb2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='preço tabela 2'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_preco_tb3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='preço tabela 3'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_un_medida',
            field=models.DecimalField(decimal_places=2, help_text='Unidade em kilograma', max_digits=3, verbose_name='unidade de medida'),
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_quantidade', models.PositiveIntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rufos.Pedido')),
                ('pedido_item_preco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rufos.Cliente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rufos.Produto')),
            ],
        ),
    ]
