# Generated by Django 3.0 on 2020-01-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0008_auto_20200127_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_produtos',
            field=models.ManyToManyField(to='rufos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
