# Generated by Django 3.0 on 2020-01-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rufos', '0010_auto_20200128_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_lista_precos',
            field=models.CharField(choices=[('TB1', 'Tabela 1'), ('TB2', 'Tabela 2'), ('TB3', 'Tabela 3')], max_length=3, verbose_name='tabela de preços'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rufos.Cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_pagamento',
            field=models.CharField(choices=[('Cre', 'Crédito'), ('Deb', 'Débito'), ('Din', 'Dinheiro')], max_length=3, verbose_name='tipo de pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.CharField(choices=[('ent', 'Entregue'), ('con', 'Confirmado'), ('can', 'Cancelado')], default='con', max_length=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sub total'),
        ),
    ]
